#cloud-config
package_update: true
packages:
  - openssh-server
users:
  - name: pavois
    groups: [sudo]
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDqLDS8p8qYu+9G2mg90wQyVzLYz4SdIIfOSkGqT0bnc bob@master1
runcmd:
  - systemctl enable --now ssh
