import type { APIRoute } from 'astro';
import matrix from '../data/platform-matrix.json';

/**
 * The platform verification matrix, served as the artefact it is.
 *
 * #351 asks for machine-readable evidence, not a table a human has to scrape. This is the same file
 * the page renders, generated by `mise run gen:platform-matrix` from the golden-path campaigns and
 * sanitised at generation time: the emitter refuses to write a record that still carries an
 * address, a login or a home directory.
 *
 * Language-neutral on purpose, so it sits at the site root rather than under /en/ or /fr/: a state
 * name is not translated, and a consumer should not have to pick a language to read a verdict.
 */
export const GET: APIRoute = () =>
  new Response(JSON.stringify(matrix, null, 2) + '\n', {
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  });
